// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pb/sum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 int32 `protobuf:"varint,1,opt,name=Num1,proto3" json:"Num1,omitempty"`
	Num2 int32 `protobuf:"varint,2,opt,name=Num2,proto3" json:"Num2,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_pb_sum_proto_rawDescGZIP(), []int{0}
}

func (x *Number) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *Number) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type SumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums *Number `protobuf:"bytes,1,opt,name=Nums,proto3" json:"Nums,omitempty"`
}

func (x *SumReq) Reset() {
	*x = SumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumReq) ProtoMessage() {}

func (x *SumReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumReq.ProtoReflect.Descriptor instead.
func (*SumReq) Descriptor() ([]byte, []int) {
	return file_pb_sum_proto_rawDescGZIP(), []int{1}
}

func (x *SumReq) GetNums() *Number {
	if x != nil {
		return x.Nums
	}
	return nil
}

type SumResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *SumResp) Reset() {
	*x = SumResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResp) ProtoMessage() {}

func (x *SumResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResp.ProtoReflect.Descriptor instead.
func (*SumResp) Descriptor() ([]byte, []int) {
	return file_pb_sum_proto_rawDescGZIP(), []int{2}
}

func (x *SumResp) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_pb_sum_proto protoreflect.FileDescriptor

var file_pb_sum_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x73, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x73, 0x75, 0x6d, 0x22, 0x30, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x75, 0x6d,
	0x31, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x4e, 0x75, 0x6d, 0x32, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x1f, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x73, 0x75, 0x6d, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x4e, 0x75, 0x6d, 0x73,
	0x22, 0x21, 0x0a, 0x07, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x2e, 0x0a, 0x0a, 0x53, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x20, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x12, 0x0b, 0x2e, 0x73, 0x75, 0x6d, 0x2e, 0x53,
	0x75, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x73, 0x75, 0x6d, 0x2e, 0x53, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_sum_proto_rawDescOnce sync.Once
	file_pb_sum_proto_rawDescData = file_pb_sum_proto_rawDesc
)

func file_pb_sum_proto_rawDescGZIP() []byte {
	file_pb_sum_proto_rawDescOnce.Do(func() {
		file_pb_sum_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_sum_proto_rawDescData)
	})
	return file_pb_sum_proto_rawDescData
}

var file_pb_sum_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_sum_proto_goTypes = []interface{}{
	(*Number)(nil),  // 0: sum.Number
	(*SumReq)(nil),  // 1: sum.SumReq
	(*SumResp)(nil), // 2: sum.SumResp
}
var file_pb_sum_proto_depIdxs = []int32{
	0, // 0: sum.SumReq.Nums:type_name -> sum.Number
	1, // 1: sum.SumService.Sum:input_type -> sum.SumReq
	2, // 2: sum.SumService.Sum:output_type -> sum.SumResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_sum_proto_init() }
func file_pb_sum_proto_init() {
	if File_pb_sum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_sum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_sum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_sum_proto_goTypes,
		DependencyIndexes: file_pb_sum_proto_depIdxs,
		MessageInfos:      file_pb_sum_proto_msgTypes,
	}.Build()
	File_pb_sum_proto = out.File
	file_pb_sum_proto_rawDesc = nil
	file_pb_sum_proto_goTypes = nil
	file_pb_sum_proto_depIdxs = nil
}
